      - name: Commit sitemap
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main

