name: Generate Sitemap

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cicirello/generate-sitemap@v1
        with:
          base-url: https://kreuzfahrtsuche.corecruises.de
          sitemap-format: xml

      - name: Set authenticated remote
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}

      - name: Commit sitemap
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes"
          git push origin HEAD:main
